name: Generate Exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Build JAR
        run: |
          ./mvnw clean install

      - name: Generate Exe
        run: |
    

      - name: Upload Exe
        uses: actions/upload-artifact@v2
        with:
          name: my-exe
          path: NAN
